#ifndef __MDM_OBJECTID_H__
#define __MDM_OBJECTID_H__


/*
 * This file is automatically generated from the data-model spreadsheet.
 * Do not modify this file directly - You will lose all your changes the
 * next time this file is generated!
 */


/*!\file mdm_objectid.h 
 * \brief Automatically generated header file mdm_objectid.h
 */


/*! \brief InternetGatewayDevice. */
#define MDMOID_IGD  1

/*! \brief InternetGatewayDevice.X_5067F0_AutoexecCmd.{i}. */
#define MDMOID_AUTOEXEC_CMD  2

/*! \brief InternetGatewayDevice.X_5067F0_DebugPortMirrorCfg. */
#define MDMOID_DEBUG_PORT_MIRROR_CFG  3

/*! \brief InternetGatewayDevice.DeviceInfo. */
#define MDMOID_IGD_DEVICE_INFO  4

/*! \brief InternetGatewayDevice.DeviceInfo.X_5067F0_DualImage. */
#define MDMOID_DUAL_IMG  5

/*! \brief InternetGatewayDevice.DeviceInfo.MemoryStatus. */
#define MDMOID_MEMORY_STATUS  6

/*! \brief InternetGatewayDevice.DeviceInfo.ProcessStatus. */
#define MDMOID_PROCESS_STATUS  7

/*! \brief InternetGatewayDevice.DeviceInfo.ProcessStatus.Process.{i}. */
#define MDMOID_PROCESS  8

/*! \brief InternetGatewayDevice.UploadDiagnostics. */
#define MDMOID_UPLOAD_DIAGNOSTICS  9

/*! \brief InternetGatewayDevice.UploadDiagnostics.X_5067F0_Result.{i}. */
#define MDMOID_UPLOAD_DIAG_RESULT  10

/*! \brief InternetGatewayDevice.DownloadDiagnostics. */
#define MDMOID_DOWNLOAD_DIAGNOSTICS  11

/*! \brief InternetGatewayDevice.DownloadDiagnostics.X_5067F0_Result.{i}. */
#define MDMOID_DOWNLOAD_DIAG_RESULT  12

/*! \brief InternetGatewayDevice.UDPEchoConfig. */
#define MDMOID_UDP_ECHO_CFG  13

/*! \brief InternetGatewayDevice.DeviceInfo.VendorConfigFile.{i}. */
#define MDMOID_VENDOR_CONFIG_FILE  14

/*! \brief InternetGatewayDevice.CaptivePortal. */
#define MDMOID_CAPTIVE_PORTAL  15

/*! \brief InternetGatewayDevice.X_5067F0_BpaApiFlowHandle.{i}. */
#define MDMOID_BPA_API_FLOW_HANDLE  16

/*! \brief InternetGatewayDevice.X_5067F0_SyslogCfg. */
#define MDMOID_SYSLOG_CFG  17

/*! \brief InternetGatewayDevice.X_5067F0_LoginCfg. */
#define MDMOID_LOGIN_CFG  18

/*! \brief InternetGatewayDevice.X_5067F0_LoginCfg.X_5067F0_Login_Group.{i}. */
#define MDMOID_LOGIN_GRP  19

/*! \brief InternetGatewayDevice.X_5067F0_LoginCfg.X_5067F0_Login_Group.{i}.Use_Login_Info.{i}. */
#define MDMOID_USER_LOGIN_INFO  20

/*! \brief InternetGatewayDevice.X_5067F0_AppCfg. */
#define MDMOID_APP_CFG  21

/*! \brief InternetGatewayDevice.X_5067F0_AppCfg.HttpdCfg. */
#define MDMOID_HTTPD_CFG  22

/*! \brief InternetGatewayDevice.X_5067F0_AppCfg.HttpdsCfg. */
#define MDMOID_HTTPDS_CFG  23

/*! \brief InternetGatewayDevice.X_5067F0_AppCfg.Tr69cCfg. */
#define MDMOID_TR69C_CFG  24

/*! \brief InternetGatewayDevice.X_5067F0_AppCfg.Tr64cCfg. */
#define MDMOID_TR64C_CFG  25

/*! \brief InternetGatewayDevice.X_5067F0_AppCfg.SshdCfg. */
#define MDMOID_SSHD_CFG  26

/*! \brief InternetGatewayDevice.X_5067F0_AppCfg.TelnetdCfg. */
#define MDMOID_TELNETD_CFG  27

/*! \brief InternetGatewayDevice.X_5067F0_AppCfg.ConsoledCfg. */
#define MDMOID_CONSOLED_CFG  28

/*! \brief InternetGatewayDevice.X_5067F0_AppCfg.SmdCfg. */
#define MDMOID_SMD_CFG  29

/*! \brief InternetGatewayDevice.X_5067F0_AppCfg.SskCfg. */
#define MDMOID_SSK_CFG  30

/*! \brief InternetGatewayDevice.X_5067F0_AppCfg.SnmpdCfg. */
#define MDMOID_SNMPD_CFG  31

/*! \brief InternetGatewayDevice.X_5067F0_AppCfg.FtpdCfg. */
#define MDMOID_FTPD_CFG  32

/*! \brief InternetGatewayDevice.X_5067F0_AppCfg.TftpdCfg. */
#define MDMOID_TFTPD_CFG  33

/*! \brief InternetGatewayDevice.X_5067F0_AppCfg.PppdCfg. */
#define MDMOID_PPPD_CFG  34

/*! \brief InternetGatewayDevice.X_5067F0_AppCfg.IcmpCfg. */
#define MDMOID_ICMP_CFG  35

/*! \brief InternetGatewayDevice.X_5067F0_AppCfg.UpnpCfg. */
#define MDMOID_UPNP_CFG  36

/*! \brief InternetGatewayDevice.X_5067F0_AppCfg.DnsProxyCfg. */
#define MDMOID_DNS_PROXY_CFG  37

/*! \brief InternetGatewayDevice.X_5067F0_AppCfg.DectdCfg. */
#define MDMOID_DECTD_CFG  38

/*! \brief InternetGatewayDevice.X_5067F0_AppCfg.VectoringCfg. */
#define MDMOID_VECTORING_CFG  39

/*! \brief InternetGatewayDevice.X_5067F0_AppCfg.OmcidCfg. */
#define MDMOID_OMCID_CFG  40

/*! \brief InternetGatewayDevice.X_5067F0_AppCfg.LaserdCfg. */
#define MDMOID_LASERD_CFG  41

/*! \brief InternetGatewayDevice.X_5067F0_AppCfg.OmciPmdCfg. */
#define MDMOID_OMCI_PMD_CFG  42

/*! \brief InternetGatewayDevice.X_5067F0_AppCfg.OsgidCfg. */
#define MDMOID_OSGID_CFG  43

/*! \brief InternetGatewayDevice.X_5067F0_EthernetSwitch. */
#define MDMOID_ETHERNET_SWITCH  44

/*! \brief InternetGatewayDevice.X_5067F0_PwrMngtCfg. */
#define MDMOID_PWR_MNGT  45

/*! \brief InternetGatewayDevice.X_5067F0_StandbyCfg. */
#define MDMOID_STANDBY_CFG  46

/*! \brief InternetGatewayDevice.DeviceConfig. */
#define MDMOID_DEVICE_CONFIG  47

/*! \brief InternetGatewayDevice.ManagementServer. */
#define MDMOID_MANAGEMENT_SERVER  48

/*! \brief InternetGatewayDevice.ManagementServer.ManageableDevice.{i}. */
#define MDMOID_MANAGEABLE_DEVICE  49

/*! \brief InternetGatewayDevice.Time. */
#define MDMOID_TIME_SERVER_CFG  50

/*! \brief InternetGatewayDevice.Layer2Bridging. */
#define MDMOID_L2_BRIDGING  51

/*! \brief InternetGatewayDevice.Layer2Bridging.Bridge.{i}. */
#define MDMOID_L2_BRIDGING_ENTRY  52

/*! \brief InternetGatewayDevice.Layer2Bridging.Filter.{i}. */
#define MDMOID_L2_BRIDGING_FILTER  53

/*! \brief InternetGatewayDevice.Layer2Bridging.AvailableInterface.{i}. */
#define MDMOID_L2_BRIDGING_INTF  54

/*! \brief InternetGatewayDevice.QueueManagement. */
#define MDMOID_Q_MGMT  55

/*! \brief InternetGatewayDevice.QueueManagement.Classification.{i}. */
#define MDMOID_Q_MGMT_CLASSIFICATION  56

/*! \brief InternetGatewayDevice.QueueManagement.Policer.{i}. */
#define MDMOID_Q_MGMT_POLICER  57

/*! \brief InternetGatewayDevice.QueueManagement.Queue.{i}. */
#define MDMOID_Q_MGMT_QUEUE  58

/*! \brief InternetGatewayDevice.LANConfigSecurity. */
#define MDMOID_LANCONFIG_SECURITY  59

/*! \brief InternetGatewayDevice.X_5067F0_TraceRouteDiagObject. */
#define MDMOID_TRACE_ROUTE_DIAG  60

/*! \brief InternetGatewayDevice.X_5067F0_TraceRouteDiagObject.RouteHops.{i}. */
#define MDMOID_TRACE_ROUTE_HOPS  61

/*! \brief InternetGatewayDevice.X_5067F0_NslookupDiagObject. */
#define MDMOID_NSLOOKUP_DIAG  62

/*! \brief InternetGatewayDevice.IPPingDiagnostics. */
#define MDMOID_IP_PING_DIAG  63

/*! \brief InternetGatewayDevice.TraceRouteDiagnostics. */
#define MDMOID_TRACE_ROUTE_DIAGNOSTICS  64

/*! \brief InternetGatewayDevice.TraceRouteDiagnostics.RouteHops.{i}. */
#define MDMOID_TRACE_ROUTE_DIAG_HOPS  65

/*! \brief InternetGatewayDevice.X_TTNET_IGMPDiagnostics. */
#define MDMOID_IGMP_DIAGNOSTICS  66

/*! \brief InternetGatewayDevice.EponSoftwareImage.{i}. */
#define MDMOID_EPON_SOFTWARE_IMAGE  67

/*! \brief InternetGatewayDevice.LANDevice.{i}. */
#define MDMOID_LAN_DEV  68

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_5067F0_IgmpSnoopingConfig. */
#define MDMOID_IGMP_SNOOPING_CFG  69

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement. */
#define MDMOID_LAN_HOST_CFG  70

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.IPInterface.{i}. */
#define MDMOID_LAN_IP_INTF  71

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.IPInterface.{i}.X_5067F0_IPv6LanIntfAddress. */
#define MDMOID_I_PV6_LAN_INTF_ADDR  72

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.IPInterface.{i}.X_5067F0_IPv6LanIntfAddress.DelegatedAddress.{i}. */
#define MDMOID_DELEGATED_ADDRESS  73

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.IPInterface.{i}.X_5067F0_FirewallException.{i}. */
#define MDMOID_LAN_IP_INTF_FIREWALL_EXCEPTION  74

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.IPInterface.{i}.X_5067F0_IpFilterCfg.{i}. */
#define MDMOID_IP_FILTER_CFG  75

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.DHCPStaticAddress.{i}. */
#define MDMOID_DHCP_STATIC_ADDR  76

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.DHCPOption.{i}. */
#define MDMOID_LAN_HOST_OPTION  77

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.DHCPConditionalServingPool.{i}. */
#define MDMOID_DHCP_CONDITIONAL_SERVING  78

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANHostConfigManagement.DHCPConditionalServingPool.{i}.DHCPOption.{i}. */
#define MDMOID_DHCP_COND_SERV_OPTION  79

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_5067F0_IPv6LANHostConfigManagement. */
#define MDMOID_I_PV6_LAN_HOST_CFG  80

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_5067F0_IPv6LANHostConfigManagement.RadvdConfigManagement. */
#define MDMOID_RADVD_CONFIG_MGT  81

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_5067F0_IPv6LANHostConfigManagement.RadvdConfigManagement.X_5067F0_DNSSLInfo. */
#define MDMOID_DNSSL_INFO  82

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_5067F0_IPv6LANHostConfigManagement.RadvdConfigManagement.ULAPrefixInfo. */
#define MDMOID_ULA_PREFIX_INFO  83

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_5067F0_IPv6LANHostConfigManagement.RadvdConfigManagement.PrefixInformation.{i}. */
#define MDMOID_PREFIX_INFO  84

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_5067F0_IPv6LANHostConfigManagement.X_5067F0_MldSnoopingConfig. */
#define MDMOID_MLD_SNOOPING_CFG  85

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_5067F0_IPv6LANHostConfigManagement.RejectPDValue.{i}. */
#define MDMOID_PD_CFG  86

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANEthernetInterfaceConfig.{i}. */
#define MDMOID_LAN_ETH_INTF  87

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANEthernetInterfaceConfig.{i}.Stats. */
#define MDMOID_LAN_ETH_INTF_STATS  88

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANUSBInterfaceConfig.{i}. */
#define MDMOID_LAN_USB_INTF  89

/*! \brief InternetGatewayDevice.LANDevice.{i}.LANUSBInterfaceConfig.{i}.Stats. */
#define MDMOID_LAN_USB_INTF_STATS  90

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}. */
#define MDMOID_LAN_WLAN  91

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.AssociatedDevice.{i}. */
#define MDMOID_LAN_WLAN_ASSOCIATED_DEVICE_ENTRY  92

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.WEPKey.{i}. */
#define MDMOID_LAN_WLAN_WEP_KEY  93

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.PreSharedKey.{i}. */
#define MDMOID_LAN_WLAN_PRE_SHARED_KEY  94

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.Stats. */
#define MDMOID_LAN_WLAN_STATS  95

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.APWMMParameter.{i}. */
#define MDMOID_APWMM_PARAMETER  96

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.STAWMMParameter.{i}. */
#define MDMOID_STAWMM_PARAMETER  97

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_5067F0_WlanAdapter. */
#define MDMOID_WLAN_ADAPTER  98

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_5067F0_WlanAdapter.WlBaseCfg. */
#define MDMOID_WL_BASE_CFG  99

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_5067F0_WlanAdapter.WlStaticWdsCfg.{i}. */
#define MDMOID_WL_STATIC_WDS_CFG  100

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_5067F0_WlanAdapter.WlWdsCfg.{i}. */
#define MDMOID_WL_WDS_CFG  101

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_5067F0_WlanAdapter.WlScanWdsCfg.{i}. */
#define MDMOID_WL_SCAN_WDS_CFG  102

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_5067F0_WlanAdapter.WlMimoCfg. */
#define MDMOID_WL_MIMO_CFG  103

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_5067F0_WlanAdapter.WlWmmCfg. */
#define MDMOID_WL_WMM_CFG  104

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_5067F0_WlanAdapter.WlWMMCfg.WlAPWmmParameterCfg.{i}. */
#define MDMOID_AP_WMM_PARAMETER_CFG  105

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_5067F0_WlanAdapter.WlWMMCfg.WlSTAWmmParameterCfg.{i}. */
#define MDMOID_STA_WMM_PARAMETER_CFG  106

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_5067F0_WlanAdapter.WlSesCfg. */
#define MDMOID_WL_SES_CFG  107

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_5067F0_WlanAdapter.WlVirtIntfCfg.{i}. */
#define MDMOID_WL_VIRT_INTF_CFG  108

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_5067F0_WlanAdapter.VirtIntf.{i}.WlMacFltCfg.{i}. */
#define MDMOID_WL_MAC_FLT  109

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_5067F0_WlanAdapter.VirtIntf.{i}.WlKey64Cfg.{i}. */
#define MDMOID_WL_KEY64_CFG  110

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_5067F0_WlanAdapter.VirtIntf.{i}.WlKey128Cfg.{i}. */
#define MDMOID_WL_KEY128_CFG  111

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_5067F0_WlanAdapter.VirtIntf.{i}.WlWpsCfg. */
#define MDMOID_WL_WPS_CFG  112

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_5067F0_WlanAdapter.ScanTimeSet. */
#define MDMOID_SCAN_TIME_SET  113

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.X_5067F0_WLANVirtMbssConfiguration.{i}. */
#define MDMOID_LAN_WLAN_VIRT_MBSS  114

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.WPS. */
#define MDMOID_LAN_WLAN_WPS  115

/*! \brief InternetGatewayDevice.LANDevice.{i}.WLANConfiguration.{i}.WPS.Registrar.{i}. */
#define MDMOID_LAN_WLAN_WPS_REGISTRAR  116

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_5067F0_LANMocaInterfaceConfig.{i}. */
#define MDMOID_LAN_MOCA_INTF  117

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_5067F0_LANMocaInterfaceConfig.{i}.Status. */
#define MDMOID_LAN_MOCA_INTF_STATUS  118

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_5067F0_LANMocaInterfaceConfig.{i}.Stats. */
#define MDMOID_LAN_MOCA_INTF_STATS  119

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_5067F0_LANEponInterfaceConfig.{i}. */
#define MDMOID_LAN_EPON_INTF  120

/*! \brief InternetGatewayDevice.LANDevice.{i}.X_5067F0_LANEponInterfaceConfig.{i}.Stats. */
#define MDMOID_LAN_EPON_INTF_STATS  121

/*! \brief InternetGatewayDevice.LANDevice.{i}.Hosts. */
#define MDMOID_LAN_HOSTS  122

/*! \brief InternetGatewayDevice.LANDevice.{i}.Hosts.Host.{i}. */
#define MDMOID_LAN_HOST_ENTRY  123

/*! \brief InternetGatewayDevice.LANDevice.{i}.Hosts.Host6.{i}. */
#define MDMOID_I_PV6_LAN_HOST_ENTRY  124

/*! \brief InternetGatewayDevice.X_5067F0_HostsIconState.{i}. */
#define MDMOID_LAN_HOST_ICON_STATE  125

/*! \brief InternetGatewayDevice.WANDevice.{i}. */
#define MDMOID_WAN_DEV  126

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANCommonInterfaceConfig. */
#define MDMOID_WAN_COMMON_INTF_CFG  127

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_5067F0_XTM_Interface_Stats.{i}. */
#define MDMOID_XTM_INTERFACE_STATS  128

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig. */
#define MDMOID_WAN_DSL_INTF_CFG  129

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.X_5067F0_BertTest. */
#define MDMOID_WAN_BERT_TEST  130

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.Stats. */
#define MDMOID_WAN_DSL_INTF_STATS  131

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.Stats.Total. */
#define MDMOID_WAN_DSL_INTF_STATS_TOTAL  132

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.Stats.Showtime. */
#define MDMOID_WAN_DSL_INTF_STATS_SHOWTIME  133

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.Stats.LastShowtime. */
#define MDMOID_WAN_DSL_INTF_STATS_LAST_SHOWTIME  134

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.Stats.CurrentDay. */
#define MDMOID_WAN_DSL_INTF_STATS_CURRENT_DAY  135

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.Stats.QuarterHour. */
#define MDMOID_WAN_DSL_INTF_STATS_QUARTER_HOUR  136

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLInterfaceConfig.TestParams. */
#define MDMOID_WAN_DSL_TEST_PARAMS  137

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANEthernetInterfaceConfig. */
#define MDMOID_WAN_ETH_INTF  138

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANEthernetInterfaceConfig.X_5067F0_IPv6Address.{i}. */
#define MDMOID_I_PV6_ADDR  139

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANEthernetInterfaceConfig.Stats. */
#define MDMOID_WAN_ETH_INTF_STATS  140

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_5067F0_WANMocaInterfaceConfig. */
#define MDMOID_WAN_MOCA_INTF  141

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_5067F0_WANMocaInterfaceConfig.Status. */
#define MDMOID_WAN_MOCA_INTF_STATUS  142

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_5067F0_WANMocaInterfaceConfig.Stats. */
#define MDMOID_WAN_MOCA_INTF_STATS  143

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_5067F0_EponInterfaceConfig. */
#define MDMOID_WAN_EPON_INTF  144

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_5067F0_EponInterfaceConfig.Stats. */
#define MDMOID_WAN_EPON_INTF_STATS  145

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_5067F0_L2tpAcIntfConfig. */
#define MDMOID_L2TP_AC_INTF_CONFIG  146

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_5067F0_WANPonInterfaceConfig. */
#define MDMOID_WAN_PON_INTF  147

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_5067F0_WANPonInterfaceConfig.Stats. */
#define MDMOID_WAN_PON_INTF_STATUS  148

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANDSLDiagnostics. */
#define MDMOID_WAN_DSL_DIAG  149

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_5067F0_WANDSLDiagnostics. */
#define MDMOID_WAN_DSL_PROPRIETARY_DIAG  150

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_5067F0_WANDSLDiagnostics.PeakLineNoise. */
#define MDMOID_WAN_DSL_DIAG_PLN  151

/*! \brief InternetGatewayDevice.WANDevice.{i}.X_5067F0_WANDSLDiagnostics.NonLinearity. */
#define MDMOID_WAN_DSL_DIAG_NON_LINEARITY  152

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}. */
#define MDMOID_WAN_CONN_DEVICE  153

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.X_5067F0_WANATMF4EndToEndLoopbackDiagnostics. */
#define MDMOID_WAN_ATM_F4_END_TO_END_LOOPBACK_DIAG  154

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.X_5067F0_WANATMF4LoopbackDiagnostics. */
#define MDMOID_WAN_ATM_F4_LOOPBACK_DIAG  155

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.X_5067F0_WANATMF5EndToEndLoopbackDiagnostics. */
#define MDMOID_WAN_ATM_F5_END_TO_END_LOOPBACK_DIAG  156

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.X_5067F0_WANGPONLinkConfig. */
#define MDMOID_WAN_GPON_LINK_CFG  157

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.X_5067F0_WANEPONLinkConfig. */
#define MDMOID_WAN_EPON_LINK_CFG  158

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANDSLLinkConfig. */
#define MDMOID_WAN_DSL_LINK_CFG  159

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANDSLLinkConfig.X_5067F0_ATM_PARMS. */
#define MDMOID_WAN_DSL_ATM_PARAMS  160

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANATMF5LoopbackDiagnostics. */
#define MDMOID_WAN_ATM5_LOOPBACK_DIAG  161

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPTMLinkConfig. */
#define MDMOID_WAN_PTM_LINK_CFG  162

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANEthernetLinkConfig. */
#define MDMOID_WAN_ETH_LINK_CFG  163

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.X_5067F0_L2tpAcLinkConfig. */
#define MDMOID_L2TP_AC_LINK_CONFIG  164

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.X_5067F0_WWANInterfaceConfig. */
#define MDMOID_WWAN_INTERFACE_CONFIG  165

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.X_5067F0_WWANInterfaceConfig.Stats. */
#define MDMOID_WWAN_INTERFACE_CONFIG_STATS  166

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.X_5067F0_WWANBudgetControl. */
#define MDMOID_WWAN_BUDGET_CONTROL  167

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.X_5067F0_WWANPingCheck. */
#define MDMOID_WWAN_PING_CHECK  168

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}. */
#define MDMOID_WAN_IP_CONN  169

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.PortMapping.{i}. */
#define MDMOID_WAN_IP_CONN_PORTMAPPING  170

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.X_5067F0_UPNPPortMappingRule.{i}. */
#define MDMOID_UPNP_IP_PORTMAPPING  171

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.X_5067F0_PortTriggering.{i}. */
#define MDMOID_WAN_IP_CONN_PORT_TRIGGERING  172

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.X_5067F0_FirewallException.{i}. */
#define MDMOID_WAN_IP_CONN_FIREWALL_EXCEPTION  173

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.X_5067F0_MacFilterObj. */
#define MDMOID_MAC_FILTER  174

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.X_5067F0_MacFilterObj.X_5067F0_MacFilterCfg.{i}. */
#define MDMOID_MAC_FILTER_CFG  175

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.Stats. */
#define MDMOID_WAN_IP_CONN_STATS  176

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANIPConnection.{i}.X_5067F0_EthernetWAN_MAC. */
#define MDMOID_IP_ETHERNET_WAN_MAC  177

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPPPConnection.{i}. */
#define MDMOID_WAN_PPP_CONN  178

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPPPConnection.{i}.PortMapping.{i}. */
#define MDMOID_WAN_PPP_CONN_PORTMAPPING  179

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPPPConnection.{i}.X_5067F0_UPNPPortMappingRule.{i}. */
#define MDMOID_UPNP_PPP_PORTMAPPING  180

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPPPConnection.{i}.X_5067F0_PortTriggering.{i}. */
#define MDMOID_WAN_PPP_CONN_PORT_TRIGGERING  181

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPPPConnection.{i}.X_5067F0_FirewallException.{i}. */
#define MDMOID_WAN_PPP_CONN_FIREWALL_EXCEPTION  182

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPPPConnection.{i}.Stats. */
#define MDMOID_WAN_PPP_CONN_STATS  183

/*! \brief InternetGatewayDevice.WANDevice.{i}.WANConnectionDevice.{i}.WANPPPConnection.{i}.X_5067F0_EthernetWAN_MAC. */
#define MDMOID_PPP_ETHERNET_WAN_MAC  184

/*! \brief InternetGatewayDevice.X_TTNET. */
#define MDMOID_XTTNET  185

/*! \brief InternetGatewayDevice.X_TTNET.Configuration. */
#define MDMOID_CONFIGUR  186

/*! \brief InternetGatewayDevice.X_TTNET.Configuration.Syslog. */
#define MDMOID_CON_SYSLOG  187

/*! \brief InternetGatewayDevice.X_TTNET.Configuration.Telnet. */
#define MDMOID_CON_TELNET  188

/*! \brief InternetGatewayDevice.X_TTNET.Configuration.ICMP. */
#define MDMOID_ICM_P  189

/*! \brief InternetGatewayDevice.X_TTNET.Configuration.IGMPProxy. */
#define MDMOID_IGMP_PROXY  190

/*! \brief InternetGatewayDevice.X_TTNET.Configuration.RTSP_ALG. */
#define MDMOID_RTSPAL_G  191

/*! \brief InternetGatewayDevice.X_TTNET.Configuration.SIP_ALG. */
#define MDMOID_SIPAL_G  192

/*! \brief InternetGatewayDevice.X_TTNET.Configuration.L2TP_ALG. */
#define MDMOID_TPAL_G  193

/*! \brief InternetGatewayDevice.X_TTNET.Configuration.H323_ALG. */
#define MDMOID_AL_G  194

/*! \brief InternetGatewayDevice.X_TTNET.Configuration.IPSec_ALG. */
#define MDMOID_IP_SEC_A_L_G  195

/*! \brief InternetGatewayDevice.X_TTNET.Configuration.PPTP_ALG. */
#define MDMOID_PPTPAL_G  196

/*! \brief InternetGatewayDevice.X_TTNET.Configuration.GUI. */
#define MDMOID_GUI  197

/*! \brief InternetGatewayDevice.X_TTNET.Configuration.GUI.AccessRights. */
#define MDMOID_ACCESS_RIGHTS  198

/*! \brief InternetGatewayDevice.X_TTNET.Configuration.GUI.AccessRights.Page. */
#define MDMOID_PAGE  199

/*! \brief InternetGatewayDevice.X_TTNET.Configuration.GUI.AccessRights.Page.NetworkSetting. */
#define MDMOID_NETWORK_SETTING  200

/*! \brief InternetGatewayDevice.X_TTNET.Configuration.GUI.AccessRights.Page.NetworkSetting.Broadband. */
#define MDMOID_B_MENU  201

/*! \brief InternetGatewayDevice.X_TTNET.Configuration.GUI.AccessRights.Page.NetworkSetting.Broadband.Broadband. */
#define MDMOID_B_PAGE  202

/*! \brief InternetGatewayDevice.X_TTNET.Configuration.GUI.AccessRights.Page.NetworkSetting.Broadband.Broadband.Internet_DSL. */
#define MDMOID_DS_L  203

/*! \brief InternetGatewayDevice.X_TTNET.Configuration.GUI.AccessRights.Page.NetworkSetting.Broadband.Broadband.Internet_WAN. */
#define MDMOID_WA_N  204

/*! \brief InternetGatewayDevice.X_TTNET.Configuration.GUI.AccessRights.Page.NetworkSetting.Broadband.Broadband.IPTV_DSL. */
#define MDMOID_IPTV_DSL  205

/*! \brief InternetGatewayDevice.X_TTNET.Configuration.GUI.AccessRights.Page.NetworkSetting.Broadband.Broadband.IPTV_WAN. */
#define MDMOID_IPTV_WAN  206

/*! \brief InternetGatewayDevice.X_TTNET.Configuration.GUI.AccessRights.Page.NetworkSetting.Broadband.Broadband.Advanced. */
#define MDMOID_ADVANCED  207

/*! \brief InternetGatewayDevice.X_TTNET.Configuration.GUI.AccessRights.Page.NetworkSetting.Wireless. */
#define MDMOID_W_MENU  208

/*! \brief InternetGatewayDevice.X_TTNET.Configuration.GUI.AccessRights.Page.NetworkSetting.Wireless.General. */
#define MDMOID_G_PAGE  209

/*! \brief InternetGatewayDevice.X_TTNET.Configuration.GUI.AccessRights.Page.NetworkSetting.Wireless.MoreAP. */
#define MDMOID_MORE_A_P  210

/*! \brief InternetGatewayDevice.X_TTNET.Configuration.GUI.AccessRights.Page.NetworkSetting.Wireless.WPS. */
#define MDMOID_WPS  211

/*! \brief InternetGatewayDevice.X_TTNET.Configuration.GUI.AccessRights.Page.NetworkSetting.Wireless.WMM. */
#define MDMOID_WMM  212

/*! \brief InternetGatewayDevice.X_TTNET.Configuration.GUI.AccessRights.Page.NetworkSetting.Wireless.Others. */
#define MDMOID_OTHERS  213

/*! \brief InternetGatewayDevice.X_TTNET.Configuration.GUI.AccessRights.Page.NetworkSetting.HomeNetworking. */
#define MDMOID_H_MENU  214

/*! \brief InternetGatewayDevice.X_TTNET.Configuration.GUI.AccessRights.Page.NetworkSetting.HomeNetworking.LANSetup. */
#define MDMOID_LAN_SETUP  215

/*! \brief InternetGatewayDevice.X_TTNET.Configuration.GUI.AccessRights.Page.NetworkSetting.HomeNetworking.LANVLAN. */
#define MDMOID_LANVLAN  216

/*! \brief InternetGatewayDevice.X_TTNET.Configuration.GUI.AccessRights.Page.NetworkSetting.Routing. */
#define MDMOID_R_MENU  217

/*! \brief InternetGatewayDevice.X_TTNET.Configuration.GUI.AccessRights.Page.NetworkSetting.NAT. */
#define MDMOID_N_MENU  218

/*! \brief InternetGatewayDevice.X_TTNET.Configuration.GUI.AccessRights.Page.NetworkSetting.NAT.ALG. */
#define MDMOID_ALG_PAGE  219

/*! \brief InternetGatewayDevice.X_TTNET.Configuration.GUI.AccessRights.Page.Security. */
#define MDMOID_SECURITY  220

/*! \brief InternetGatewayDevice.X_TTNET.Configuration.GUI.AccessRights.Page.Security.Firewall. */
#define MDMOID_F_MENU  221

/*! \brief InternetGatewayDevice.X_TTNET.Configuration.GUI.AccessRights.Page.Security.Firewall.DoS. */
#define MDMOID_DO_S  222

/*! \brief InternetGatewayDevice.X_TTNET.Configuration.GUI.AccessRights.Page.SystemMonitor. */
#define MDMOID_S_MENU  223

/*! \brief InternetGatewayDevice.X_TTNET.Configuration.GUI.AccessRights.Page.SystemMonitor.Log. */
#define MDMOID_LOG  224

/*! \brief InternetGatewayDevice.X_TTNET.Configuration.GUI.AccessRights.Page.Maintenance. */
#define MDMOID_M_MENU  225

/*! \brief InternetGatewayDevice.X_TTNET.Configuration.GUI.AccessRights.Page.Maintenance.RemoteMGMT. */
#define MDMOID_MGM_T  226

/*! \brief InternetGatewayDevice.X_TTNET.Configuration.GUI.AccessRights.Page.Maintenance.Time. */
#define MDMOID_TIME  227

/*! \brief InternetGatewayDevice.X_TTNET.Configuration.GUI.AccessRights.Page.Maintenance.LogSetting. */
#define MDMOID_LOG_SETTING  228

/*! \brief InternetGatewayDevice.X_TTNET.Configuration.GUI.AccessRights.Page.Maintenance.FirmwareUpgrade. */
#define MDMOID_FIRMWARE_UPGRADE  229

/*! \brief InternetGatewayDevice.X_TTNET.Configuration.GUI.AccessRights.Page.Maintenance.Configuration. */
#define MDMOID_PAG_E  230

/*! \brief InternetGatewayDevice.X_TTNET.Function. */
#define MDMOID_FUNC  231

/*! \brief InternetGatewayDevice.X_TTNET.Function.SyslogUpload. */
#define MDMOID_FUNC_SYSLOG_UP  232

/*! \brief InternetGatewayDevice.X_TTNET.Firewall. */
#define MDMOID_TTNET_FIREWALL  233

/*! \brief InternetGatewayDevice.X_TTNET.UPnP. */
#define MDMOID_TTNET_U_PN_P  234

/*! \brief InternetGatewayDevice.X_TTNET.UPnP.Device. */
#define MDMOID_TTNET_U_PN_P_DEVICE  235

/*! \brief InternetGatewayDevice.X_TTNET.Users. */
#define MDMOID_TTNET_USERS  236

/*! \brief InternetGatewayDevice.X_TTNET.Users.User.{i}. */
#define MDMOID_TTNET_USERS_USER  237

/*! \brief InternetGatewayDevice.X_TTNET.UserInterface. */
#define MDMOID_TTNET_USER_INTERFACE_CFG  238

/*! \brief InternetGatewayDevice.X_TTNET.UserInterface.RemoteAccess. */
#define MDMOID_REMOTE_ACCESS  239

/*! \brief InternetGatewayDevice.X_TTNET.UserInterface.LocalAccess. */
#define MDMOID_LOCAL_ACCESS  240

/*! \brief InternetGatewayDevice.X_TTNET.PortMirroring. */
#define MDMOID_TTNET_PORT_MIRRORING  241

/*! \brief InternetGatewayDevice.X_TTNET.PacketCapture. */
#define MDMOID_PACKET_CAPTURE  242

/*! \brief InternetGatewayDevice.X_TTNET.PacketCapture.Upload. */
#define MDMOID_CAPTURE_UPLOAD  243

/*! \brief InternetGatewayDevice.X_5067F0_PortMappingEntry.{i}. */
#define MDMOID_WAN_CONN_PORTMAPPING  244

/*! \brief InternetGatewayDevice.X_5067F0_VcAutoHunt. */
#define MDMOID_VC_AUTO_HUNT  245

/*! \brief InternetGatewayDevice.X_5067F0_VcAutoHunt.VcHuntInfo.{i}. */
#define MDMOID_VC_HUNT_INFO  246

/*! \brief InternetGatewayDevice.X_5067F0_VcAutoHunt.VcHuntInfo.{i}.VcHuntRule.{i}. */
#define MDMOID_VC_HUNT_RULE  247

/*! \brief InternetGatewayDevice.X_5067F0_VlanAutoHunt. */
#define MDMOID_VLAN_AUTO_HUNT  248

/*! \brief InternetGatewayDevice.X_5067F0_VlanAutoHunt.VlanHuntInfo.{i}. */
#define MDMOID_VLAN_HUNT_INFO  249

/*! \brief InternetGatewayDevice.X_5067F0_VlanAutoHunt.HuntWAN.{i}.VlanHuntRule.{i}. */
#define MDMOID_VLAN_HUNT_RULE  250

/*! \brief InternetGatewayDevice.Layer3Forwarding. */
#define MDMOID_L3_FORWARDING  251

/*! \brief InternetGatewayDevice.Layer3Forwarding.Forwarding.{i}. */
#define MDMOID_L3_FORWARDING_ENTRY  252

/*! \brief InternetGatewayDevice.GRE. */
#define MDMOID_GRE  253

/*! \brief InternetGatewayDevice.GRE.Tunnel.{i}. */
#define MDMOID_GRE_TUNN  254

/*! \brief InternetGatewayDevice.GRE.Tunnel.{i}.Stats. */
#define MDMOID_GRE_TUNN_INTF_STATS  255

/*! \brief InternetGatewayDevice.GRE.Tunnel.{i}.Interface.{i}. */
#define MDMOID_GRE_TUNN_INTF  256

/*! \brief InternetGatewayDevice.GRE.Tunnel.{i}.Interface.{i}.Stats. */
#define MDMOID_GRE_INTERFACE_STATS  257

/*! \brief InternetGatewayDevice.GRE.Filter.{i}. */
#define MDMOID_GRE_FILTER  258

/*! \brief InternetGatewayDevice.X_5067F0_IPv6Layer3Forwarding. */
#define MDMOID_I_PV6_L3_FORWARDING  259

/*! \brief InternetGatewayDevice.X_5067F0_IPv6Layer3Forwarding.IPv6Forwarding.{i}. */
#define MDMOID_I_PV6_L3_FORWARDING_ENTRY  260

/*! \brief InternetGatewayDevice.Services. */
#define MDMOID_SERVICES  261

/*! \brief InternetGatewayDevice.Services.StorageService.{i}. */
#define MDMOID_STORAGE_SERVICE  262

/*! \brief InternetGatewayDevice.Services.StorageService.{i}.UserAccount.{i}. */
#define MDMOID_USER_ACCOUNT  263

/*! \brief InternetGatewayDevice.Services.StorageService.{i}.Capabilites. */
#define MDMOID_CAPABILITES  264

/*! \brief InternetGatewayDevice.Services.StorageService.{i}.NetInfo. */
#define MDMOID_NETWORK_INFO  265

/*! \brief InternetGatewayDevice.Services.StorageService.{i}.NetworkServer. */
#define MDMOID_NETWORK_SERVER  266

/*! \brief InternetGatewayDevice.Services.StorageService.{i}.PhysicalMedium.{i}. */
#define MDMOID_PHYSICAL_MEDIUM  267

/*! \brief InternetGatewayDevice.Services.StorageService.{i}.LogicalVolume.{i}. */
#define MDMOID_LOGICAL_VOLUME  268

/*! \brief InternetGatewayDevice.Services.StorageService.{i}.LogicalVolume.{i}.Folder.{i}. */
#define MDMOID_FOLDER  269

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}. */
#define MDMOID_VOICE  270

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_Call.{i}. */
#define MDMOID_VOICE_CALL_LIST  271

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_Call.{i}.NewFlag. */
#define MDMOID_VOICE_CALL_NEW_FLAG  272

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_Call.{i}.NumberOfMissedCalls. */
#define MDMOID_VOICE_CALL_NUMBER_OF_MISSED_CALLS  273

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_Call.{i}.Number. */
#define MDMOID_VOICE_CALL_NUMBER  274

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_Call.{i}.Name. */
#define MDMOID_VOICE_CALL_NAME  275

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_Call.{i}.DateTime. */
#define MDMOID_VOICE_CALL_DATE_TIME  276

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_Call.{i}.LineName. */
#define MDMOID_VOICE_CALL_LINE_NAME  277

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_Call.{i}.LineId. */
#define MDMOID_VOICE_CALL_LINE_ID  278

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_Call.{i}.CallType. */
#define MDMOID_VOICE_CALL_TYPE  279

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_InternalName.{i}. */
#define MDMOID_VOICE_INTERNAL_NAME_LIST  280

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_InternalName.{i}.TerminalNumber. */
#define MDMOID_VOICE_TERMINAL_NUMBER  281

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_InternalName.{i}.Name. */
#define MDMOID_VOICE_INTERNAL_NAME  282

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_Contact.{i}. */
#define MDMOID_VOICE_CONTACT_LIST  283

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_Contact.{i}.Name. */
#define MDMOID_VOICE_CONTACT_NAME  284

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_Contact.{i}.FirstName. */
#define MDMOID_VOICE_CONTACT_FIRST_NAME  285

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_Contact.{i}.ContactNumber. */
#define MDMOID_VOICE_CONTACT_NUMBER  286

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_Contact.{i}.Melody. */
#define MDMOID_VOICE_CONTACT_MELODY  287

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_Contact.{i}.LineId. */
#define MDMOID_VOICE_CONTACT_LINE_ID  288

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_SupportList.{i}. */
#define MDMOID_VOICE_DECT_SUPPORT_LIST  289

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.Capabilities. */
#define MDMOID_VOICE_CAP  290

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.Capabilities.SIP. */
#define MDMOID_VOICE_CAP_SIP  291

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.Capabilities.MGCP. */
#define MDMOID_VOICE_CAP_MGCP  292

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.Capabilities.Codecs.{i}. */
#define MDMOID_VOICE_CAP_CODECS  293

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}. */
#define MDMOID_VOICE_PROF  294

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.ServiceProviderInfo. */
#define MDMOID_VOICE_PROF_PROVIDER  295

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.SIP. */
#define MDMOID_VOICE_PROF_SIP  296

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.SIP.EventSubscribe.{i}. */
#define MDMOID_VOICE_PROF_SIP_SUBSCRIBE  297

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.MGCP. */
#define MDMOID_VOICE_PROF_MGCP  298

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.RTP. */
#define MDMOID_VOICE_PROF_RTP  299

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.RTP.SRTP. */
#define MDMOID_VOICE_PROF_RTP_SRTP  300

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.NumberingPlan. */
#define MDMOID_VOICE_PROF_NUMBERING_PLAN  301

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.NumberingPlan.PrefixInfo.{i}. */
#define MDMOID_VOICE_PROF_NUMBERING_PLAN_PREFIX_INFO  302

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.FaxT38. */
#define MDMOID_VOICE_PROF_FAX_T38  303

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}. */
#define MDMOID_VOICE_LINE  304

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.SIP. */
#define MDMOID_VOICE_LINE_SIP  305

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.CallingFeatures. */
#define MDMOID_VOICE_LINE_CALLING_FEATURES  306

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.VoiceProcessing. */
#define MDMOID_VOICE_LINE_PROCESSING  307

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.Codec. */
#define MDMOID_VOICE_LINE_CODEC  308

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.Codec.List.{i}. */
#define MDMOID_VOICE_LINE_CODEC_LIST  309

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.Session.{i}. */
#define MDMOID_VOICE_LINE_SESSION  310

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.Stats. */
#define MDMOID_VOICE_LINE_STATS  311

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_5067F0_LineSetting. */
#define MDMOID_VOICE_LINE_SETTING  312

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_5067F0_DectLineSetting.LineName. */
#define MDMOID_VOICE_LINE_NAME  313

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_5067F0_DectLineSetting.LineId. */
#define MDMOID_VOICE_LINE_DECT_LINE_ID  314

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_5067F0_DectLineSetting.AttachedHandset. */
#define MDMOID_VOICE_LINE_ATTACHED_HANDSET  315

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_5067F0_DectLineSetting.Melody. */
#define MDMOID_VOICE_LINE_MELODY  316

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_5067F0_DectLineSetting.DialingPrefix. */
#define MDMOID_VOICE_LINE_DIALING_PREFIX  317

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_5067F0_DectLineSetting.Volumn. */
#define MDMOID_VOICE_LINE_VOLUMN  318

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_5067F0_DectLineSetting.BlockedNumber. */
#define MDMOID_VOICE_LINE_BLOCKED_NUMBER  319

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_5067F0_DectLineSetting.MultiCallMode. */
#define MDMOID_VOICE_LINE_MULTI_CALL_MODE  320

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_5067F0_DectLineSetting.IntrusionCall. */
#define MDMOID_VOICE_LINE_INTRUSION_CALL  321

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_5067F0_DectLineSetting.CLIR. */
#define MDMOID_CLI_R  322

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.VoiceProfile.{i}.Line.{i}.X_5067F0_DectLineSetting.CallForwarding. */
#define MDMOID_VOICE_LINE_CALL_FORWARDING  323

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_PhyIntfMgn. */
#define MDMOID_VOICE_PHY_INTF_MGN  324

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_PhyIntfMgn.PhyInterface.{i}. */
#define MDMOID_VOICE_PHY_INTF  325

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_PhyIntfMgn.PhyInterface.{i}.X_5067F0_FXS.{i}. */
#define MDMOID_VOICE_PHY_INTF_FXS  326

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_PhyIntfMgn.PhyInterface.{i}.X_5067F0_FXO.{i}. */
#define MDMOID_VOICE_PHY_INTF_FXO  327

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.PhyInterface.{i}. */
#define MDMOID_PHY_INTF  328

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_PSTN.{i}. */
#define MDMOID_VOICE_PSTN  329

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_Ntr. */
#define MDMOID_VOICE_NTR  330

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_Ntr.History.{i}. */
#define MDMOID_VOICE_NTR_HISTORY  331

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.DECTInterface. */
#define MDMOID_VOICE_DECT_SYSTEM_SETTING  332

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.DECTInterface.Handset.{i}. */
#define MDMOID_DECT_HANDSET  333

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.DECTInterface.PINCode. */
#define MDMOID_VOICE_DECT_PIN_CODE  334

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.DECTInterface.ClockMaster. */
#define MDMOID_VOICE_DECT_CLOCK_MASTER  335

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.DECTInterface.ResetBase. */
#define MDMOID_VOICE_DECT_RESET_BASE  336

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.DECTInterface.FirmwareVersion. */
#define MDMOID_VOICE_DECT_FIRMWARE_VERSION  337

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.DECTInterface.HardwareVersion. */
#define MDMOID_VOICE_DECT_HARDWARE_VERSION  338

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.DECTInterface.EEPROMVersion. */
#define MDMOID_EEPROM_VERSION  339

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_Common. */
#define MDMOID_VOICE_COMMON  340

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_VoicePhoneBook.{i}. */
#define MDMOID_VOICE_PHONE_BOOK  341

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_FXO. */
#define MDMOID_VOICE_FXO  342

/*! \brief InternetGatewayDevice.Services.VoiceService.{i}.X_5067F0_FXO.Port.{i}. */
#define MDMOID_VOICE_FXO_PORT  343

/*! \brief InternetGatewayDevice.X_5067F0_AutoFWUpgrade. */
#define MDMOID_AU_F_W  344

/*! \brief InternetGatewayDevice.Services.X_5067F0_VOIPFilter. */
#define MDMOID_VOIP_FILTER  345

/*! \brief InternetGatewayDevice.Services.X_5067F0_VOIPFilter.Domain.{i}. */
#define MDMOID_VOIP_FILTER_DOMAIN  346

/*! \brief InternetGatewayDevice.X_5067F0_SnmpCfg. */
#define MDMOID_SNMP_CFG  347

/*! \brief InternetGatewayDevice.X_5067F0_EmailNotificationCfg.{i}. */
#define MDMOID_EMAIL_NOTIFICATION  348

/*! \brief InternetGatewayDevice.X_5067F0_SecDmzHostCfg. */
#define MDMOID_SEC_DMZ_HOST_CFG  349

/*! \brief InternetGatewayDevice.X_5067F0_AccessTimeRestriction.{i}. */
#define MDMOID_ACCESS_TIME_RESTRICTION  350

/*! \brief InternetGatewayDevice.X_5067F0_ParentalCtl.{i}. */
#define MDMOID_PARENTAL_CTL  351

/*! \brief InternetGatewayDevice.X_5067F0_ParentalCtl.{i}.X_5067F0_Url.{i}. */
#define MDMOID_URL  352

/*! \brief InternetGatewayDevice.X_5067F0_ParentalCtl.{i}.X_5067F0_NetworkService.{i}. */
#define MDMOID_PC_NETWORK_SRV  353

/*! \brief InternetGatewayDevice.X_5067F0_ParentalCtl.{i}.X_5067F0_NetworkService.{i}.X_5067F0_Service.{i}. */
#define MDMOID_PC_SERVICE  354

/*! \brief InternetGatewayDevice.X_5067F0_UrlFilterCfg. */
#define MDMOID_URL_FILTER_CFG  355

/*! \brief InternetGatewayDevice.X_5067F0_UrlFilterCfg.X_5067F0_UrlFilterListCfgObj.{i}. */
#define MDMOID_URL_FILTER_LIST  356

/*! \brief InternetGatewayDevice.X_5067F0_MacFilterObj. */
#define MDMOID_MSTC_MAC_FILTER  357

/*! \brief InternetGatewayDevice.X_5067F0_MacFilterObj.X_5067F0_MacFilterCfg.{i}. */
#define MDMOID_MSTC_MAC_FILTER_CFG  358

/*! \brief InternetGatewayDevice.X_5067F0_DnsMasqCfg. */
#define MDMOID_DNS_MASQ_CFG  359

/*! \brief InternetGatewayDevice.X_5067F0_DnsRouteEntry.{i}. */
#define MDMOID_DNS_ROUTE_ENTRY  360

/*! \brief InternetGatewayDevice.X_5067F0_DDnsCfg.{i}. */
#define MDMOID_D_DNS_CFG  361

/*! \brief InternetGatewayDevice.X_5067F0_IPPCfg. */
#define MDMOID_IPP_CFG  362

/*! \brief InternetGatewayDevice.X_5067F0_DLNA. */
#define MDMOID_DLNA  363

/*! \brief InternetGatewayDevice.X_5067F0_DLNA.DmsCfg. */
#define MDMOID_DMS_CFG  364

/*! \brief InternetGatewayDevice.X_5067F0_DebugPortMirroringCfg.{i}. */
#define MDMOID_WAN_DEBUG_PORT_MIRRORING_CFG  365

/*! \brief InternetGatewayDevice.X_5067F0_IPSecCfg.{i}. */
#define MDMOID_IP_SEC_CFG  366

/*! \brief InternetGatewayDevice.X_5067F0_CertificateCfg.{i}. */
#define MDMOID_CERTIFICATE_CFG  367

/*! \brief InternetGatewayDevice.X_5067F0_WapiCertificate. */
#define MDMOID_WAPI_CERTIFICATE  368

/*! \brief InternetGatewayDevice.X_5067F0_WapiCertificate.WapiAsCertificate. */
#define MDMOID_WAPI_AS_CERTIFICATE  369

/*! \brief InternetGatewayDevice.X_5067F0_WapiCertificate.WapiIssuedCertificate. */
#define MDMOID_WAPI_ISSUED_CERTIFICATE  370

/*! \brief InternetGatewayDevice.X_5067F0_NetworkConfig. */
#define MDMOID_NETWORK_CONFIG  371

/*! \brief InternetGatewayDevice.X_5067F0_InterfaceControl. */
#define MDMOID_INTERFACE_CONTROL  372

/*! \brief InternetGatewayDevice.X_5067F0_P8021agCfg. */
#define MDMOID_P8021AG_CFG  373

/*! \brief InternetGatewayDevice.X_5067F0_IGMPCfg. */
#define MDMOID_IGMP_CFG  374

/*! \brief InternetGatewayDevice.IGMP.GroupStats.{i}. */
#define MDMOID_GROUP_STATS  375

/*! \brief InternetGatewayDevice.IGMP.GroupStats.{i}.Total. */
#define MDMOID_GROUP_STATS_TOTAL  376

/*! \brief InternetGatewayDevice.IGMP.HostStats.{i}. */
#define MDMOID_HOST_STATS  377

/*! \brief InternetGatewayDevice.IGMP.HostStats.{i}.Total. */
#define MDMOID_HOST_STATS_TOTAL  378

/*! \brief InternetGatewayDevice.X_5067F0_IEEE8021xAuthenticationSupplicant.{i}. */
#define MDMOID_WAN8021_X  379

/*! \brief InternetGatewayDevice.X_5067F0_MLDCfg. */
#define MDMOID_MLD_CFG  380

/*! \brief InternetGatewayDevice.X_5067F0_IPTunnel.{i}. */
#define MDMOID_IP_TUNNEL  381

/*! \brief InternetGatewayDevice.X_5067F0_IPTunnel.{i}.V4inV6Tunnel.{i}. */
#define MDMOID_IPV4IN_IPV6_TUNNEL  382

/*! \brief InternetGatewayDevice.X_5067F0_IPTunnel.{i}.V6inV4Tunnel.{i}. */
#define MDMOID_IPV6IN_IPV4_TUNNEL  383

/*! \brief InternetGatewayDevice.X_ITU_T_ORG. */
#define MDMOID_ITU_T_ORG  384

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4. */
#define MDMOID_G_984_4  385

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement. */
#define MDMOID_EQUIPMENT_MANAGEMENT  386

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement.OntG. */
#define MDMOID_ONT_G  387

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement.Ont2G. */
#define MDMOID_ONT2_G  388

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement.OntData. */
#define MDMOID_ONT_DATA  389

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement.SoftwareImage.{i}. */
#define MDMOID_SOFTWARE_IMAGE  390

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement.CardHolder.{i}. */
#define MDMOID_CARD_HOLDER  391

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement.CircuitPack.{i}. */
#define MDMOID_CIRCUIT_PACK  392

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement.PowerShedding.{i}. */
#define MDMOID_POWER_SHEDDING  393

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EquipmentManagement.PortMappingPackageG.{i}. */
#define MDMOID_PORT_MAPPING_PACKAGE_G  394

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement. */
#define MDMOID_ANI_MANAGEMENT  395

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.AniG.{i}. */
#define MDMOID_ANI_G  396

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.TCont.{i}. */
#define MDMOID_T_CONT  397

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.GemPortNetworkCtp.{i}. */
#define MDMOID_GEM_PORT_NETWORK_CTP  398

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.GemInterworkingTp.{i}. */
#define MDMOID_GEM_INTERWORKING_TP  399

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.MulticastGemInterworkingTp.{i}. */
#define MDMOID_MULTICAST_GEM_INTERWORKING_TP  400

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.MulticastGemInterworkingTp.{i}.MulticastAddressTable.{i}. */
#define MDMOID_GEM_INTERWORKING_TP_MULTICAST_ADDRESS_TABLE  401

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.GemPortPmHistoryData.{i}. */
#define MDMOID_GEM_PORT_PM_HISTORY_DATA  402

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.GalEthernetProfile.{i}. */
#define MDMOID_GAL_ETHERNET_PROFILE  403

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.GalEthernetPmHistoryData.{i}. */
#define MDMOID_GAL_ETHERNET_PM_HISTORY_DATA  404

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.AniManagement.FecPmHistoryData.{i}. */
#define MDMOID_FEC_PM_HISTORY_DATA  405

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices. */
#define MDMOID_LAYER2_DATA_SERVICES  406

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgeServiceProfile.{i}. */
#define MDMOID_MAC_BRIDGE_SERVICE_PROFILE  407

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.X_5067F0_MacBridgeServiceProfile.{i}. */
#define MDMOID_BC_MAC_BRIDGE_SERVICE_PROFILE  408

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgeConfigData.{i}. */
#define MDMOID_MAC_BRIDGE_CONFIG_DATA  409

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePmHistoryData.{i}. */
#define MDMOID_MAC_BRIDGE_PM_HISTORY_DATA  410

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePortConfigData.{i}. */
#define MDMOID_MAC_BRIDGE_PORT_CONFIG_DATA  411

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePortDesignationData.{i}. */
#define MDMOID_MAC_BRIDGE_PORT_DESIGNATION_DATA  412

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePortFilterTableData.{i}. */
#define MDMOID_MAC_BRIDGE_PORT_FILTER_TABLE_DATA  413

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePortFilterTableData.{i}.MacFilterTable.{i}. */
#define MDMOID_MAC_FILTER_TABLE  414

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePortFilterPreAssignTable.{i}. */
#define MDMOID_MAC_BRIDGE_PORT_FILTER_PRE_ASSIGN_TABLE  415

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePortBridgeTableData.{i}. */
#define MDMOID_MAC_BRIDGE_PORT_BRIDGE_TABLE_DATA  416

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePortBridgeTableData.{i}.BridgeTable.{i}. */
#define MDMOID_BRIDGE_TABLE  417

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MacBridgePortPmHistoryData.{i}. */
#define MDMOID_MAC_BRIDGE_PORT_PM_HISTORY_DATA  418

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MapperServiceProfile.{i}. */
#define MDMOID_MAPPER_SERVICE_PROFILE  419

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.X_5067F0_MapperServiceProfile.{i}. */
#define MDMOID_BC_MAPPER_SERVICE_PROFILE  420

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.VlanTaggingFilterData.{i}. */
#define MDMOID_VLAN_TAGGING_FILTER_DATA  421

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.VlanTaggingOperationConfigurationData.{i}. */
#define MDMOID_VLAN_TAGGING_OPERATION_CONFIGURATION_DATA  422

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.ExtendedVlanTaggingOperationConfigurationData.{i}. */
#define MDMOID_EXTENDED_VLAN_TAGGING_OPERATION_CONFIGURATION_DATA  423

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.ExtendedVlanTaggingOperationConfigurationData.{i}.ReceivedFrameVlanTaggingOperationTable.{i}. */
#define MDMOID_RECEIVED_FRAME_VLAN_TAGGING_OPERATION_TABLE  424

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MulticastOperationsProfile.{i}. */
#define MDMOID_MULTICAST_OPERATIONS_PROFILE  425

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MulticastOperationsProfile.{i}.DynamicAccessControlListTable.{i}. */
#define MDMOID_DYNAMIC_ACCESS_CONTROL_LIST_TABLE  426

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MulticastOperationsProfile.{i}.StaticAccessControlListTable.{i}. */
#define MDMOID_STATIC_ACCESS_CONTROL_LIST_TABLE  427

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MulticastOperationsProfile.{i}.LostGroupsListTable.{i}. */
#define MDMOID_LOST_GROUPS_LIST_TABLE  428

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MulticastSubscriberConfigInfo.{i}. */
#define MDMOID_MULTICAST_SUBSCRIBER_CONFIG_INFO  429

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MulticastSubscriberMonitor.{i}. */
#define MDMOID_MULTICAST_SUBSCRIBER_MONITOR  430

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.MulticastSubscriberMonitor.{i}.ActiveGroupsListTable.{i}. */
#define MDMOID_ACTIVE_GROUPS_LIST_TABLE  431

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.X_5067F0_MulticastSubscriberMonitor.{i}. */
#define MDMOID_BC_MULTICAST_SUBSCRIBER_MONITOR  432

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.X_5067F0_MulticastSubscriberMonitor.{i}.MulticastSubscriber.{i}. */
#define MDMOID_MULTICAST_SUBSCRIBER  433

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.UpstreamEthernetFramePmHistoryData.{i}. */
#define MDMOID_UPSTREAM_ETHERNET_FRAME_PM_HISTORY_DATA  434

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer2DataServices.DownstreamEthernetFramePmHistoryData.{i}. */
#define MDMOID_DOWNSTREAM_ETHERNET_FRAME_PM_HISTORY_DATA  435

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices. */
#define MDMOID_LAYER3_DATA_SERVICES  436

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.IpHostConfigData.{i}. */
#define MDMOID_IP_HOST_CONFIG_DATA  437

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.X_5067F0_IpHostConfigData.{i}. */
#define MDMOID_BC_IP_HOST_CONFIG_DATA  438

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.IpHostPmHistoryData.{i}. */
#define MDMOID_IP_HOST_PM_HISTORY_DATA  439

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.Ipv6HostConfigData.{i}. */
#define MDMOID_IPV6_HOST_CONFIG_DATA  440

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.Ipv6HostConfigData.{i}.CurrentAddressTable.{i}. */
#define MDMOID_IPV6_CURRENT_ADDRESS_TABLE  441

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.Ipv6HostConfigData.{i}.CurrentDefaultRouterTable.{i}. */
#define MDMOID_IPV6_CURRENT_DEFAULT_ROUTER_TABLE  442

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.Ipv6HostConfigData.{i}.CurrentDnsTable.{i}. */
#define MDMOID_IPV6_CURRENT_DNS_TABLE  443

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.Ipv6HostConfigData.{i}.CurrentOnlinkPrefixTable.{i}. */
#define MDMOID_IPV6_CURRENT_ONLINK_PREFIX_TABLE  444

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.X_BROADCOM_COM_Ipv6HostConfigData.{i}. */
#define MDMOID_BC_IPV6_HOST_CONFIG_DATA  445

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.Layer3DataServices.TcpUdpConfigData.{i}. */
#define MDMOID_TCP_UDP_CONFIG_DATA  446

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EthernetServices. */
#define MDMOID_ETHERNET_SERVICES  447

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EthernetServices.PptpEthernetUni.{i}. */
#define MDMOID_PPTP_ETHERNET_UNI  448

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EthernetServices.EthernetPmHistoryData.{i}. */
#define MDMOID_ETHERNET_PM_HISTORY_DATA  449

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EthernetServices.EthernetPmHistoryData2.{i}. */
#define MDMOID_ETHERNET_PM_HISTORY_DATA2  450

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EthernetServices.EthernetPmHistoryData3.{i}. */
#define MDMOID_ETHERNET_PM_HISTORY_DATA3  451

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.EthernetServices.VirtualEthernetInterfacePoint.{i}. */
#define MDMOID_VIRTUAL_ETHERNET_INTERFACE_POINT  452

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices. */
#define MDMOID_VOICE_SERVICES  453

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.PptpPotsUni.{i}. */
#define MDMOID_PPTP_POTS_UNI  454

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.SipUserData.{i}. */
#define MDMOID_SIP_USER_DATA  455

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.SipAgentConfigData.{i}. */
#define MDMOID_SIP_AGENT_CONFIG_DATA  456

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.VoIpVoiceCtp.{i}. */
#define MDMOID_VO_IP_VOICE_CTP  457

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.VoIpMediaProfile.{i}. */
#define MDMOID_VO_IP_MEDIA_PROFILE  458

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.VoiceServiceProfile.{i}. */
#define MDMOID_VOICE_SERVICE  459

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.RtpProfileData.{i}. */
#define MDMOID_RTP_PROFILE_DATA  460

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.VoIpAppServiceProfile.{i}. */
#define MDMOID_VO_IP_APP_SERVICE_PROFILE  461

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.VoiceFeatureAccessCodes.{i}. */
#define MDMOID_VOICE_FEATURE_ACCESS_CODES  462

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.NetworkDialPlanTable.{i}. */
#define MDMOID_NETWORK_DIAL_PLAN_TABLE  463

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.NetworkDialPlanTable.{i}.DialPlanTable.{i}. */
#define MDMOID_DIAL_PLAN_TABLE  464

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.VoIpLineStatus.{i}. */
#define MDMOID_VO_IP_LINE_STATUS  465

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.CallControlPmHistoryData.{i}. */
#define MDMOID_CALL_CONTROL_PM_HISTORY_DATA  466

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.RtpPmHistoryData.{i}. */
#define MDMOID_RTP_PM_HISTORY_DATA  467

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.SipAgentPmHistoryData.{i}. */
#define MDMOID_SIP_AGENT_PM_HISTORY_DATA  468

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.SipCallInitPmHistoryData.{i}. */
#define MDMOID_SIP_CALL_INIT_PM_HISTORY_DATA  469

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.MgcConfigData.{i}. */
#define MDMOID_MGC_CONFIG_DATA  470

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.MgcPmHistoryData.{i}. */
#define MDMOID_MGC_PM_HISTORY_DATA  471

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.VoiceServices.VoIpConfigData.{i}. */
#define MDMOID_VO_IP_CONFIG_DATA  472

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.MocaServices. */
#define MDMOID_MOCA_SERVICES  473

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.MocaServices.PptpMocaUni.{i}. */
#define MDMOID_PPTP_MOCA_UNI  474

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.MocaServices.X_5067F0_PptpMocaUni.{i}. */
#define MDMOID_BRCM_PPTP_MOCA_UNI  475

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.MocaServices.X_5067F0_MocaStatus.{i}. */
#define MDMOID_MOCA_STATUS  476

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.MocaServices.X_5067F0_MocaStats.{i}. */
#define MDMOID_MOCA_STATS  477

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.MocaServices.MocaEthernetPmHistoryData.{i}. */
#define MDMOID_MOCA_ETHERNET_PM_HISTORY_DATA  478

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.MocaServices.MocaInterfacePmHistoryData.{i}. */
#define MDMOID_MOCA_INTERFACE_PM_HISTORY_DATA  479

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.MocaServices.MocaInterfacePmHistoryData.{i}.NodeTable.{i}. */
#define MDMOID_MOCA_INTERFACE_PM_HISTORY_DATA_NODE_TABLE  480

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.TrafficManagement. */
#define MDMOID_TRAFFIC_MANAGEMENT  481

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.TrafficManagement.PriorityQueueG.{i}. */
#define MDMOID_PRIORITY_QUEUE_G  482

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.TrafficManagement.TrafficSchedulerG.{i}. */
#define MDMOID_TRAFFIC_SCHEDULER_G  483

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.TrafficManagement.GemTrafficDescriptor.{i}. */
#define MDMOID_GEM_TRAFFIC_DESCRIPTOR  484

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General. */
#define MDMOID_GENERAL  485

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.UniG.{i}. */
#define MDMOID_UNI_G  486

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.OltG. */
#define MDMOID_OLT_G  487

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.NetworkAddress.{i}. */
#define MDMOID_NETWORK_ADDRESS  488

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.AuthenticationSecurityMethod.{i}. */
#define MDMOID_AUTHENTICATION_SECURITY_METHOD  489

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.LargeString.{i}. */
#define MDMOID_LARGE_STRING  490

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.ThresholdData1.{i}. */
#define MDMOID_THRESHOLD_DATA1  491

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.ThresholdData2.{i}. */
#define MDMOID_THRESHOLD_DATA2  492

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.Omci. */
#define MDMOID_OMCI  493

/*! \brief InternetGatewayDevice.X_ITU_T_ORG.G_984_4.General.TR069ManagementServer.{i}. */
#define MDMOID_TR069_MANAGEMENT_SERVER  494

/*! \brief InternetGatewayDevice.X_5067F0_OmciSystem. */
#define MDMOID_OMCI_SYSTEM  495

/*! \brief InternetGatewayDevice.X_5067F0_GponOmciStats. */
#define MDMOID_GPON_OMCI_STATS  496

/*! \brief InternetGatewayDevice.X_5067F0_ALG. */
#define MDMOID_ALG  497

/*! \brief InternetGatewayDevice.X_5067F0_NATLoopback. */
#define MDMOID_NAT_LOOPBACK  498

/*! \brief InternetGatewayDevice.X_5067F0_PortMappingRule.{i}. */
#define MDMOID_PORTMAPPINGRULE  499

/*! \brief InternetGatewayDevice.X_5067F0_NAT_Session. */
#define MDMOID_NAT_SESSION  500

/*! \brief InternetGatewayDevice.X_5067F0_AddressMapping.{i}. */
#define MDMOID_ADDRESS_MAPPING  501

/*! \brief InternetGatewayDevice.X_5067F0_WlanNvram. */
#define MDMOID_WLAN_NVRAM  502

/*! \brief InternetGatewayDevice.X_CT_OAM. */
#define MDMOID_CTOAM  503

/*! \brief InternetGatewayDevice.X_CT_OAM.IADInfo. */
#define MDMOID_OAMIAD_INFO  504

/*! \brief InternetGatewayDevice.X_CT_OAM.GlobalParameterConfig. */
#define MDMOID_OAM_GLB_PARAM_CFG  505

/*! \brief InternetGatewayDevice.X_CT_OAM.SIPParameterConfig. */
#define MDMOID_OAMSIP_PARAM_CFG  506

/*! \brief InternetGatewayDevice.X_CT_OAM.SIPUserParameterConfig. */
#define MDMOID_OAMSIP_USR_PARAM_CFG  507

/*! \brief InternetGatewayDevice.X_CT_OAM.FAXModemConfig. */
#define MDMOID_OAMFAXMD_CFG  508

/*! \brief InternetGatewayDevice.X_CT_OAM.POTSStatus. */
#define MDMOID_OAMPOTS_STS  509

/*! \brief InternetGatewayDevice.X_CT_OAM.IADOperation. */
#define MDMOID_OAMIAD_OP  510

/*! \brief InternetGatewayDevice.X_CT_OAM.SIPDigitMap. */
#define MDMOID_OAMSIP_DGT_MP  511

/*! \brief InternetGatewayDevice.SoftwareModules. */
#define MDMOID_SW_MODULES  512

/*! \brief InternetGatewayDevice.SoftwareModules.ExecutionUnit.{i}. */
#define MDMOID_EU  513

/*! \brief InternetGatewayDevice.SoftwareModules.ExecutionUnit.{i}.Extensions. */
#define MDMOID_EXTENSIONS  514

/*! \brief InternetGatewayDevice.SoftwareModules.ExecEnv.{i}. */
#define MDMOID_EXEC_ENV  515

/*! \brief InternetGatewayDevice.SoftwareModules.DeploymentUnit.{i}. */
#define MDMOID_DU  516

/*! \brief InternetGatewayDevice.Device. */
#define MDMOID_DEVICE  517

/*! \brief InternetGatewayDevice.Device.Optical. */
#define MDMOID_DEVICE_OPTICAL  518

/*! \brief InternetGatewayDevice.Device.Optical.Interface.{i}. */
#define MDMOID_OPTICAL_INTERFACE  519

/*! \brief InternetGatewayDevice.Device.Optical.Interface.{i}.Stats. */
#define MDMOID_OPTICAL_INTERFACE_STATS  520

/*! \brief InternetGatewayDevice.X_5067F0_FirewallObj. */
#define MDMOID_MSTC_FIREWALL  521

/*! \brief InternetGatewayDevice.X_5067F0_AccessControlObj.{i}. */
#define MDMOID_MSTC_ACL  522

/*! \brief InternetGatewayDevice.X_5067F0_Schedule.{i}. */
#define MDMOID_SCHEDULE  523

/*! \brief InternetGatewayDevice.X_5067F0_AutoScheduleObj. */
#define MDMOID_MSTC_AUTO_SCHEDULE  524

/*! \brief InternetGatewayDevice.X_5067F0_ServiceObj.{i}. */
#define MDMOID_MSTC_SERVICE  525

/*! \brief InternetGatewayDevice.X_5067F0_ServiceObj.{i}.X_5067F0_ProtocolCfg.{i}. */
#define MDMOID_MSTC_PROTO_CFG  526

/*! \brief InternetGatewayDevice.X_5067F0_AccessServiceCfg. */
#define MDMOID_MSTC_ACCESS_SERVICE  527

/*! \brief InternetGatewayDevice.X_5067F0_WebUi. */
#define MDMOID_WEB_UI  528

/*! \brief InternetGatewayDevice.X_5067F0_Hosts.{i}. */
#define MDMOID_LAN_ZY_HOST_ENTRY  529

/*! \brief InternetGatewayDevice.X_5067F0_CBTFirewallObj. */
#define MDMOID_MSTC_CBT_FIREWALL  530

/*! \brief InternetGatewayDevice.X_5067F0_MultilingualConfig. */
#define MDMOID_MULTI_SELECT_LANGUAGE  531

/*! \brief InternetGatewayDevice.X_TTNET_Assia_Support. */
#define MDMOID_ASSIA_SUPPORT  532

/*! \brief maximum OID value */
#define MDM_MAX_OID 532



#endif /* __MDM_OBJECTID_H__ */
