echo ********************Generate SMT CFE END********************
cp ../../defaultcfg/100AAPP0_TE.rom ./100AAPP0_TE.rom
./CompressConfig_CFE ./100AAPP0_TE.rom ./100AAPP0_TE.rom_COMP
cat ./cfe63268nand128.bm ./100AAPP0_TE.rom_COMP > ./cfe63268nand128.tmp
./createboot --boardid=963168VX --numbermac=14 --macaddr=CC:5D:4E:00:00:01 --countrycode=FF --manufactureConfig=1 --modelid=400e --tp=0 --psisize=128 --backuppsi=y --inputfile=cfe63268nand128.tmp --outputfile=cfe63268nand128_Release_TE.bin --cfeSize=$(find . -name cfe63268nand128.bm -printf '%s')
./createboot --boardid=963168VX --numbermac=14 --macaddr=CC:5D:4E:00:00:01 --countrycode=FF --manufactureConfig=1 --modelid=400e --tp=0 --psisize=128 --empty --backuppsi=y --inputfile=cfe63268nand128.tmp --outputfile=cfe63268nand128_TE.bin --cfeSize=$(find . -name cfe63268nand128.bm -printf '%s')
echo ********************Generate SMT CFE END********************
echo ********************Generate SMT file BEGIN********************
./CompressConfig_RAS ./100AAPP0.rom ./100AAPP0.rom_COMP
./bcmZyNandImageBuilder --output bcmVMG3312-B10B_cfe_fs_kernel_NAND128_TE --chip 63268 --board 963168VX --internalversion="1.00(AAPP.7)" --externalversion="1.00(AAPP.7)" --modelid=400e --cmodelid=400e --imgdefaultfile=100AAPP0.rom_COMP --cfefile cfe63268nand128_TE.bin --rootfsfile rootfs128kb.img --include-cfe
./createZyNandimg --boardid=963168VX --numbermac=14 --macaddr=CC:5D:4E:00:00:01 --countrycode=FF --tp=0 --psisize=128 --gponsn= --gponpw= --backuppsi=y --inputfile=bcmVMG3312-B10B_cfe_fs_kernel_NAND128_TE --outputfile=bcmVMG3312-B10B_flash_image_963168VX_NAND128_TE
./createNandImage -V "1.00(AAPP.7)" -Q 1 -b 4 -e 4 -P 2048 -m 13 -t 0 -O "128" -B 128 -G 20 -M 1
./createNandImage -i bcmVMG3312-B10B_flash_image_963168VX_NAND128_TE -V "1.00(AAPP.7)" -v "220830_2243" -Q 1 -B 128 -O "128" -b 4 -e 4 -P 2048 -m 13 -t 0 -G 20 -M 0
cat common_header.img partition_header.img > product_header.img
cat product_header.img partition_image.img > bcmVMG3312-B10B_SMT_963168VX_NAND128
echo ********************Generate SMT file for 4 bit ECC END********************
echo ********************Compare SMT file for 4 bit ECC Begin********************
if [ "$(diff ./bcmVMG3312-B10B_SMT_963168VX_NAND128 ../bcmVMG3312-B10B_SMT_963168VX_NAND128)" = "" ]; then
echo -e "\033[32mThe SMT file ./bcmVMG3312-B10B_SMT_963168VX_NAND128 generated by GenSMT.sh is same as ../bcmVMG3312-B10B_SMT_963168VX_NAND128\033[0m"
else
echo -e "\033[33mThe SMT file ./bcmVMG3312-B10B_SMT_963168VX_NAND128 generated by GenSMT.sh is different as ../bcmVMG3312-B10B_SMT_963168VX_NAND128\033[0m"
fi
echo ********************Compare SMT file for 4 bit ECC END********************
rm common_header.img partition_header.img product_header.img partition_image.img
./NANDimg_gen -v "1.00(AAPP.7)" -q 1 -t large -M 1
./NANDimg_gen -f bcmVMG3312-B10B_flash_image_963168VX_NAND128_TE -v "1.00(AAPP.7)" -i 220830_2243 -S 0 -s jffs2 -c on -q 1 -p 128 -t large -o brcom -e 512 -G 50
cat common_header.img partition_header.img > product_header.img
cat product_header.img partition_image.img > bcmVMG3312-B10B_SMT_963168VX_NAND128_1_ECC
cat partition_image.img > bcmVMG3312-B10B_SMT_963168VX_NAND128_1_ECC_partition_image
echo ********************Generate SMT file for 1 bit ECC END********************
echo ********************Compare SMT file for 1 bit ECC Begin********************
if [ "$(diff ./bcmVMG3312-B10B_SMT_963168VX_NAND128_1_ECC ../bcmVMG3312-B10B_SMT_963168VX_NAND128_1_ECC)" = "" ]; then
echo -e "\033[32mThe SMT file ./bcmVMG3312-B10B_SMT_963168VX_NAND128_1_ECC generated by GenSMT.sh is same as ../bcmVMG3312-B10B_SMT_963168VX_NAND128_1_ECC\033[0m"
else
echo -e "\033[33mThe SMT file ./bcmVMG3312-B10B_SMT_963168VX_NAND128_1_ECC generated by GenSMT.sh is different as ../bcmVMG3312-B10B_SMT_963168VX_NAND128_1_ECC\033[0m"
fi
echo ********************Compare SMT file for 1 bit ECC END********************
