#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "/opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/bin/mips-linux-uclibc-gcc -fPIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -DOPENSSL_NO_KRB5 -DOPENSSL_NO_HW -DB_ENDIAN -Os -fomit-frame-pointer -Wall -DOPENSSL_NO_IDEA  -DOPENSSL_NO_BF -DOPENSSL_NO_CAST -DOPENSSL_NO_MD2 -DOPENSSL_NO_RIPEMD -DOPENSSL_NO_MDC2 -DOPENSSL_NO_DSA -DOPENSSL_NO_EC  -Werror=return-type -Werror=uninitialized -Werror=frame-larger-than=1024 -Wl,-rpath, -L/tmp/consumer/100AAPP7D0/targets/VMG3312-B10B/fs.install/lib -L/tmp/consumer/100AAPP7D0/targets/VMG3312-B10B/fs.install/lib/public -I/opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/include -Wl,-L/opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/usr/lib -Wl,-L/opt/toolchains/uclibc-crosstools-gcc-4.4.2-1/lib"
  #define PLATFORM "linux-mips"
  #define DATE "Tue Aug 30 22:34:44 EEST 2022"
#endif
